// SPDX-License-Identifier: Apache-2.0
#pragma once

namespace vibe_phone_setup::detail {
// Self-contained captive portal: no fonts, scripts, telemetry or other remote requests.
inline constexpr char kPage[] = R"PHONEPAGE(<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>made · Setup</title><style>
:root{color-scheme:dark;font:18px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#101c20;color:#f0f5ee}*{box-sizing:border-box}body{margin:0}main{max-width:590px;margin:auto;padding:26px 20px 44px}h1{font-size:32px;line-height:1.2;margin:8px 0 16px}h2{font-size:21px;margin:0 0 16px}.brand{color:#caff80;font-weight:750;letter-spacing:.06em}p{margin:12px 0}.muted{color:#b9c8c8;font-size:16px}.card{border:1px solid #395052;border-radius:20px;background:#18292c;padding:20px;margin:20px 0}label{display:block;font-weight:600;margin:18px 0 8px}label:first-child{margin-top:0}input,select,button{font:inherit;width:100%;min-height:52px;border:1px solid #657877;border-radius:12px;background:#0e1b1e;color:inherit;padding:12px}input:focus,select:focus,button:focus{outline:3px solid #caff80;outline-offset:2px}input[type=checkbox]{width:24px;min-height:24px;height:24px;margin:3px 10px 0 0;flex-shrink:0;accent-color:#caff80}.check{display:flex;align-items:flex-start;font-weight:500;gap:2px}.row{display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:center}.row label{margin:0}.row .check{margin-top:28px}button{background:#caff80;color:#142411;font-weight:750;border:0;cursor:pointer;margin-top:14px}button:disabled{opacity:.6;cursor:wait}.notice{padding:16px;border:1px solid #8bc494;border-radius:12px;overflow-wrap:anywhere}.notice.error{border-color:#ffa88c;color:#ffd3c4}fieldset{padding:0;margin:0;border:0;min-width:0}[hidden]{display:none!important}code{font-size:16px;color:#d7eabc;overflow-wrap:anywhere}.secret{letter-spacing:.06em}small{display:block;font-size:16px;color:#b9c8c8;margin-top:8px}@media(max-width:370px){main{padding:22px 16px}.card{padding:16px}.row{grid-template-columns:1fr}.row .check{margin-top:0}}
</style></head><body><main><div class="brand" id="brand">made</div><h1 data-key="title"></h1><p class="muted" data-key="intro"></p>
<form id="setup"><div class="card"><label for="mode" data-key="method"></label><select id="mode" name="mode"><option value="automatic" data-key="automatic"></option><option value="receiver" data-key="receiver"></option><option value="manual" data-key="manual"></option></select><p class="muted" id="methodHelp"></p></div>
<fieldset id="receiverFields" class="card" hidden><h2 data-key="receiverTitle"></h2><label for="receiverSsid" data-key="ssid"></label><input id="receiverSsid" maxlength="32" autocomplete="off" autocapitalize="none" spellcheck="false"><label for="receiverPassword" data-key="password"></label><input id="receiverPassword" class="secret" type="password" maxlength="63" autocomplete="new-password"><label class="check"><input id="showReceiver" type="checkbox"><span data-key="showPassword"></span></label><small data-key="receiverHelp"></small></fieldset>
<fieldset id="networkFields" class="card"><h2 data-key="wifiTitle"></h2><p id="savedWifi" class="muted"></p><label class="check"><input id="changeWifi" type="checkbox"><span data-key="changeWifi"></span></label><div id="wifiInputs" hidden><label for="wifiSsid" data-key="wifiName"></label><input id="wifiSsid" maxlength="32" autocomplete="off" autocapitalize="none" spellcheck="false"><label for="wifiPassword" data-key="password"></label><input id="wifiPassword" type="password" maxlength="63" autocomplete="new-password"><label class="check"><input id="showWifi" type="checkbox"><span data-key="showPassword"></span></label><small data-key="wifiHelp"></small></div></fieldset>
<fieldset id="manualFields" class="card" hidden><h2 data-key="manualTitle"></h2><label for="host" data-key="address"></label><input id="host" type="text" inputmode="url" maxlength="128" placeholder="https://bridge.example.com" autocomplete="off" autocapitalize="none" spellcheck="false"><small data-key="addressHelp"></small><div class="row"><div><label for="port" data-key="port"></label><input id="port" type="number" min="1" max="65535" step="1" inputmode="numeric"></div><label class="check"><input id="https" type="checkbox" checked><span>HTTPS</span></label></div></fieldset>
<div id="notice" class="notice" role="status" aria-live="polite" hidden></div><button id="submit" type="submit" data-key="save"></button></form><p class="muted" data-key="privacy"></p><p class="muted"><span data-key="fallback"></span><br><code>http://192.168.8.1</code></p></main>
<script>
'use strict';
const config=__MADE_SETUP_CONFIG__;
const messages={
zh:{title:'用手机配置连接',intro:'填写后，码得将关闭临时热点并连接你选择的网络。',method:'连接方式',automatic:'同 Wi-Fi · 自动发现',receiver:'通过 USB 接收端',manual:'手动桥接地址',automaticHelp:'让码得和电脑连接同一个 Wi-Fi。回到码得选择桥接器并核对配对码。',receiverHelpMode:'接收端插入电脑后，用电脑大盘显示的热点名称和密码连接。',manualHelp:'连接局域网地址或公网 HTTPS 地址。电脑上的桥接器需要保持运行。',receiverTitle:'接收端热点',ssid:'热点名称（SSID）',password:'密码',showPassword:'显示密码',receiverHelp:'在电脑端大盘的接收端区域查看名称和密码。新接收端使用 8 位数字密码；已有接收端也可输入原密码。',wifiTitle:'码得使用的 Wi-Fi',saved:'已保存名称：',unchanged:'保留设备现有 Wi-Fi',changeWifi:'设置或更换 Wi-Fi',wifiName:'Wi-Fi 名称（SSID）',wifiHelp:'支持 2.4 GHz Wi-Fi。密码留空表示开放网络；需要网页认证的网络请改用接收端等方式。',manualTitle:'桥接地址',address:'主机名、IP 或完整地址',addressHelp:'可直接粘贴 https://example.com:443/。地址中带端口时优先使用该端口；HTTP/HTTPS 也会自动识别。',port:'端口',save:'保存并连接',saving:'正在发送…',sent:'配置已发送。请回到码得查看连接结果，并按提示核对配对码。临时热点即将关闭。',privacy:'此页面只设置设备连接。不会设置或读取电脑端的 API Key、模型或长期配对令牌。临时入口在 10 分钟后自动关闭。',fallback:'连接临时热点后，若配置页没有自动弹出，请在浏览器打开：',networkError:'未能发送。请确认手机仍连接码得临时热点，关闭手机代理后重试；入口超时后需在码得重新打开。',requiredWifi:'请填写 Wi-Fi 名称。',requiredReceiver:'请填写接收端热点名称和密码。',requiredAddress:'请填写桥接地址。',expired:'页面已失效，请在码得重新打开手机配置。'},
en:{title:'Set up with your phone',intro:'After you save, made will close this temporary hotspot and connect to your chosen network.',method:'Connection method',automatic:'Same Wi-Fi · Discover bridge',receiver:'USB receiver',manual:'Manual bridge address',automaticHelp:'Connect made and your computer to the same Wi-Fi. Then choose the bridge on made and check the pairing code.',receiverHelpMode:'Plug the receiver into your computer, then enter the hotspot name and password shown on the dashboard.',manualHelp:'Use a local address or a public HTTPS address. Keep the bridge running on your computer.',receiverTitle:'Receiver hotspot',ssid:'Hotspot name (SSID)',password:'Password',showPassword:'Show password',receiverHelp:'Find the name and password in the receiver section of the computer dashboard. New receivers use an 8-digit password; existing passwords also work.',wifiTitle:'Wi-Fi used by made',saved:'Saved name: ',unchanged:'Keep the current Wi-Fi on made',changeWifi:'Set or change Wi-Fi',wifiName:'Wi-Fi name (SSID)',wifiHelp:'Use 2.4 GHz Wi-Fi. A blank password means an open network. For networks requiring a web sign-in, use a receiver or another connection method.',manualTitle:'Bridge address',address:'Hostname, IP, or full URL',addressHelp:'You can paste https://example.com:443/. An explicit port in the URL takes priority. HTTP/HTTPS is detected automatically.',port:'Port',save:'Save and connect',saving:'Sending…',sent:'Configuration sent. Check the connection result on made, then verify the pairing code when prompted. This hotspot will close shortly.',privacy:'This page only configures the device connection. It never reads or changes computer API keys, models, or long-term pairing tokens. This temporary page closes after 10 minutes.',fallback:'After joining the temporary hotspot, if this page does not open automatically, open:',networkError:'Could not send. Check that your phone is still on the made hotspot, turn off any phone proxy, and retry. If it expired, reopen phone setup on made.',requiredWifi:'Enter the Wi-Fi name.',requiredReceiver:'Enter the receiver hotspot name and password.',requiredAddress:'Enter the bridge address.',expired:'This page has expired. Reopen phone setup on made.'}
};
const en=config.english; const t=messages[en?'en':'zh']; const $=id=>document.getElementById(id);
document.documentElement.lang=en?'en':'zh-CN';document.title=(en?'made':'码得')+' · '+t.title;$('brand').textContent=en?'made':'码得';
for(const node of document.querySelectorAll('[data-key]'))node.textContent=t[node.dataset.key];
$('mode').value=['automatic','manual','receiver'].includes(config.mode)?config.mode:'automatic';
$('wifiSsid').value=config.wifi_ssid||'';$('receiverSsid').value=config.receiver_ssid||'';$('host').value=config.host||'';$('port').value=config.port||443;$('https').checked=config.https!==false;
$('savedWifi').textContent=config.wifi_ssid?t.saved+config.wifi_ssid:t.unchanged;
function update(){const mode=$('mode').value;$('receiverFields').hidden=mode!=='receiver';$('receiverFields').disabled=mode!=='receiver';$('networkFields').hidden=mode==='receiver';$('networkFields').disabled=mode==='receiver';$('manualFields').hidden=mode!=='manual';$('manualFields').disabled=mode!=='manual';$('methodHelp').textContent=mode==='receiver'?t.receiverHelpMode:mode==='manual'?t.manualHelp:t.automaticHelp;$('wifiInputs').hidden=!$('changeWifi').checked;}
$('mode').addEventListener('change',update);$('changeWifi').addEventListener('change',update);update();
$('showWifi').addEventListener('change',()=>{$('wifiPassword').type=$('showWifi').checked?'text':'password';});$('showReceiver').addEventListener('change',()=>{$('receiverPassword').type=$('showReceiver').checked?'text':'password';});
let portEdited=false;$('port').addEventListener('input',()=>{portEdited=true;});
$('host').addEventListener('input',()=>{const address=$('host').value.trim();if(!/^https?:\/\//i.test(address))return;try{const url=new URL(address);$('https').checked=url.protocol==='https:';if(url.port)$('port').value=url.port;else if(!portEdited)$('port').value=url.protocol==='https:'?'443':'80';}catch{}});
$('https').addEventListener('change',()=>{if($('https').checked&&$('port').value==='8788')$('port').value='443';else if(!$('https').checked&&$('port').value==='443')$('port').value='8788';});
function notice(message,error){$('notice').hidden=false;$('notice').classList.toggle('error',!!error);$('notice').textContent=message;}
$('setup').addEventListener('submit',async event=>{event.preventDefault();if($('submit').disabled)return;const mode=$('mode').value;const payload={nonce:config.nonce,mode};
if(mode==='receiver'){payload.receiver_ssid=$('receiverSsid').value;payload.receiver_password=$('receiverPassword').value;if(!payload.receiver_ssid||!payload.receiver_password){notice(t.requiredReceiver,true);return;}}
else{if($('changeWifi').checked){payload.wifi_ssid=$('wifiSsid').value;payload.wifi_password=$('wifiPassword').value;if(!payload.wifi_ssid){notice(t.requiredWifi,true);return;}}if(mode==='manual'){payload.host=$('host').value.trim();payload.port=Number($('port').value);payload.https=$('https').checked;if(!payload.host){notice(t.requiredAddress,true);return;}}}
$('submit').disabled=true;$('submit').textContent=t.saving;
try{const response=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});const result=await response.json();if(!response.ok){notice(result.message||t.expired,true);$('submit').disabled=false;$('submit').textContent=t.save;return;}$('wifiPassword').value='';$('receiverPassword').value='';for(const field of document.querySelectorAll('input,select'))field.disabled=true;notice(t.sent,false);$('submit').textContent=t.sent;$('submit').hidden=true;}
catch{notice(t.networkError,true);$('submit').disabled=false;$('submit').textContent=t.save;}});
</script></body></html>)PHONEPAGE";
} // namespace vibe_phone_setup::detail
