#!/usr/bin/env python3
"""Encode the approved app artwork as a 112px PNG and an LVGL ARGB8888 asset.

Requires Pillow only when preparing assets, never on the running bridge.
"""
import argparse
from pathlib import Path


def main():
    from PIL import Image, ImageOps
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('png', type=Path)
    parser.add_argument('c_source', type=Path)
    args = parser.parse_args()
    with Image.open(args.source) as original:
        rgba = ImageOps.exif_transpose(original).convert('RGBA')
        rgba = ImageOps.contain(rgba, (112, 112), Image.Resampling.LANCZOS)
        icon = Image.new('RGBA', (112, 112))
        icon.alpha_composite(rgba, ((112 - rgba.width) // 2, (112 - rgba.height) // 2))
    args.png.parent.mkdir(parents=True, exist_ok=True)
    icon.save(args.png)
    # LVGL ARGB8888 uses straight-alpha BGRA bytes on the ESP32-S3.
    pixels = icon.tobytes('raw', 'BGRA')
    assert len(pixels) == 112 * 112 * 4
    rows = ['    ' + ', '.join(f'0x{byte:02x}' for byte in pixels[i:i + 24]) + ','
            for i in range(0, len(pixels), 24)]
    source = '''// SPDX-License-Identifier: Apache-2.0
// Generated by tools/build-app-icon.py from the approved artwork in assets/branding/.
#include "lvgl.h"

const uint8_t img_app_vibe_map[] = {
''' + '\n'.join(rows) + '''
};

const lv_image_dsc_t img_app_vibe = {
    .header.cf = LV_COLOR_FORMAT_ARGB8888,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = 112,
    .header.h = 112,
    .header.stride = 112 * 4,
    .data_size = sizeof(img_app_vibe_map),
    .data = img_app_vibe_map,
};
'''
    args.c_source.write_text(source, encoding='utf-8')
    print(f'Prepared {args.png} and {args.c_source}: 112x112 RGBA, {len(pixels)} bytes')


if __name__ == '__main__':
    main()
